### ISSUE TITLE
Script does not work for normal user login

### ISSUE THREAD

**Issue by mahescho** [ThomasKur/ModernAndSecureWorkplace#4]
For me the  Windows-D-COPE-ScriptMapPrinters-x64.ps1 script does not work with normal users logging in. What I get is an error:

`HRESULT 0x800702e4 Add-Printer`

This is because normal users are not allowed to install printer drivers. To fix this add this:

     New-Item -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\' -Name 'Printers'
     New-Item -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers' -Name 'PointAndPrint'
     New-ItemProperty -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'RestrictDriverInstallationToAdministrators' -Value '0'  -PropertyType 'dword'

in the "run as system" section. Sorry, I'm to lazy for a pull request :)

Better solution:

https://www.anoopcnair.com/prevent-users-from-installing-printer-drivers-using-intune/

**Comment by ThomasKur** [comment]
Thanks for the feedback. But Microsoft introduced these keys and limited driver installation to mitigate Print Nightmare and related vulnerabilities. So, the recommended way would be to preinstall the print drivers which are required. Otherwise, you have to set the proposed keys, but I will not add them by default to the script.
